### ISSUE TITLE
Generate an invoice from a HTML template in weird characters

### ISSUE THREAD

**Issue by Teolone88** [creecros/Task2pdf#37]
I am trying to generate an invoice with dompdf from a [HTML ](https://github.com/sparksuite/simple-html-invoice-template/tree/master)template but I get gibberish.
I am following your method and I do not understand what is going wrong here.
`%PDF-1.7 1 0 obj << /Type /Catalog /Outlines 2 0 R /Pages 3 0 R >> endobj 2 0 obj << /Type /Outlines /Count 0 >> endobj 3 0 obj << /Type /Pages /Kids [6 0 R ] /Count 1 /Resources << /ProcSet 4 0 R /Font << /F1 8 0 R /F2 13 0 R >> >> /MediaBox [0.000 0.000 612.000 792.000] >> endobj 4 0 obj [/PDF /Text ] endobj 5 0 obj << /Producer (��dompdf 2.0.8 + CPDF) /CreationDate (D:20240607171428+02'00') /ModDate (D:20240607171428+02'00') /Title (��A simple, clean, and responsive HTML invoice template) >> endobj 6 0 `

I was using the FDPF library but I get the same issue and now I am sure the problem is mine as your plugin works fine.

```
use Dompdf\Dompdf;
use Dompdf\Options;
use Kanboard\Controller\BaseController;
use Kanboard\Model\UserMetadataModel;
use Kanboard\Model\ProjectModel;
use Kanboard\Model\CommentModel;
use Kanboard\Model\TaskLinkModel;
use Kanboard\Model\ColumnModel;
use Kanboard\Model\ColorModel;
use Kanboard\Model\TaskTagModel;
use Kanboard\Model\TaskFileModel;
use Kanboard\Model\TaskModel;
use Kanboard\Filter\TaskProjectFilter;
```

```
    public function printProjectInvoice($task_ids, $project)
    {
        // instantiate and use t$options = new Options();
        $options = new Options();
        $options->set('isRemoteEnabled', 'true');
        $options->set('defaultFont', 'DejaVu Sans');
        $options->set('fontHeightRatio', '.9');
        $options->set('isJavascriptEnabled', 'true');
        set_time_limit(600);
        $dompdf = new Dompdf($options);
        $dompdf->setBasePath('/var/www/app/data/');

        foreach ($task_ids as $task_id) {
            $task = $this->taskFinderModel->getDetails($task_id);
            $commentSortingDirection = $this->userMetadataCacheDecorator->get(UserMetadataModel::KEY_COMMENT_SORTING_DIRECTION, 'ASC');

            $html = $this->template->render('Invoicer:invoiceLayout/invoice', array(
                'project' => $this->projectModel->getById($task['project_id']),
                'task' => $task,
                'title' => $task['title'],
                'no_layout' => true,
                'auto_refresh' => true,
                'not_editable' => true,
            ));

        }

        $dompdf->loadHtml($html);


        // (Optional) Setup the paper size and orientation
        $dompdf->setPaper('letter', 'portrait');

        // Render the HTML as PDF
        $dompdf->render();
        if ($this->configModel->get('task2pdf_embed_projects', 1) == 1) {
            $cpdf = $dompdf->get_canvas()->get_cpdf();
            foreach ($files_to_embed as $file) {
                $cpdf->addEmbeddedFile(
                    FILES_DIR. '/' . $file['path'],
                    $file['name'],
                    ''
                );
            }
        }

        // Output the generated PDF to Browser inline or as PDF download
        $dompdf->stream($project['id'] . '_' . $project['name'] . '.pdf', ["Attachment" => false]);
    }
```

From 

```
    public function invoiceProjectOpen(array $values = array())
    {
        $status = array(TaskModel::STATUS_OPEN);

        $project = $this->getProject();
        $task_ids = $this->db
        ->table(TaskModel::TABLE)
        ->eq(TaskModel::TABLE.'.project_id', $project['id'])
        ->in(TaskModel::TABLE.'.is_active', $status)
        ->asc(TaskModel::TABLE.'.id')
        ->findAllByColumn(TaskModel::TABLE.'.id');
        self::printProjectInvoice($task_ids, $project);
    }
```

Can you please help me?
I am going bananas here.
Best,
Teo

**Comment by Teolone88** [comment]
This is what i get printing echoing the html
![image](https://github.com/creecros/Task2pdf/assets/36920983/094b3920-b4ff-4696-83cb-37fd6d070ac1)
It appears that the values are not passed.

**Comment by creecros** [comment]
I doubt I'd be much help unless I actually get my hands on it. I'm better at hands on, so I can see everything, and adjust accordingly.

**Comment by creecros** [comment]
But feel free to add me to a repo if you have one. Then I can play around.

**Comment by Teolone88** [comment]
Hi creecros,
I have uploaded the plugin temporary here https://github.com/Teolone88/Invoicer
I am reverse engineering your method.

- Create the attach on the plugin.php to show the icon in the dropdown

![image](https://github.com/creecros/Task2pdf/assets/36920983/44c8a57c-859e-456c-88c3-e2d60ecb96dd)

- Pull a bunch of field values with a modal form (The select is modified as select2, just added a multiple and [] to the name to be able to select multiple values). At the moment if you don't select anything it goes banana and i need to fix it.

![image](https://github.com/creecros/Task2pdf/assets/36920983/599b743c-b22d-4257-97ef-2300c7d35274)

- The Save should theoretically generate the PDF based on the HTML template taken from here https://github.com/sparksuite/simple-html-invoice-template/blob/master/website/index.html

However, if I echo the HTML before the stream it pop the layout without the proper CSS (Maybe this is just a PHP constrain) but withy the stream it returns gibberish.

Please let me know if you need anything and thank you again for your availability on this.
I think overall could be a potentially good idea for the world to turn tasks into invoiceable items. Gig economy and microtransactions management.

**Comment by creecros** [comment]
I'll take a look when I get a chance.

From my experience with dompdf, I can say it kind of sucks. I had plans to find a better library, something I never got around to.

**Comment by Teolone88** [comment]
I have also used http://www.fpdf.org/ with this repo https://github.com/artkonekt/pdf-invoice but I get the same gibberish outcome. Thank you for this.

**Comment by Teolone88** [comment]
I have also tries mPDF, but failed miserably with the same gibberish. I am giving up.
Feel free to give it a try but I am not sure anymore of what I am doing wrong here.

Here my latest stream:

```
%PDF-1.4
%����
3 0 obj
<</Type /Page
/Parent 1 0 R
/MediaBox [0 0 595.280 841.890]
/TrimBox [0.000 0.000 595.280 841.890]
/Resources 2 0 R
/Group << /Type /Group /S /Transparency /CS /DeviceRGB >> 
/Contents 4 0 R>>
endobj
4 0 obj
<</Filter /FlateDecode /Length 131>>
stream
x�=�1�@�3�W<7]�ih{΂V��l�vzP�����@�H��ŉ%�C��;�޸
"���2Gn�K���.��|�A�����P�1�(9o�2P���Ы �.Ȱ�%`MG����E����:�j�<����#�
endstream
endobj
1 0 obj
<</Type /Pages
/Kids [3 0 R ]
/Count 1
/MediaBox [0 0 595.280 841.890]
>>
endobj
5 0 obj
<</Type /ExtGState
/BM /Normal
/ca 1
/CA 1
>>
endobj
6 0 obj
<</Type /Font
/Subtype /Type0
/BaseFont /MPDFAA+DejaVuSerifCondensed-Bold
/Encoding /Identity-H
/DescendantFonts [7 0 R]
/ToUnicode 8 0 R
>>
endobj
7 0 obj
<</Type /Font
/Subtype /CIDFontType2
/BaseFont /MPDFAA+DejaVuSerifCondensed-Bold
/CIDSystemInfo 9 0 R
/FontDescriptor 10 0 R
/DW 540
/W [ 32 [ 313 395 469 754 626 855 813 275 426 426 470 754 313 374 313 329 ]
 48 57 626 58 59 332 60 62 754 63 [ 527 900 698 760 716 780 686 639 769 850 421 426 782 633 996 822 784 677 784 748 650 669 785 698 1011 698 642 657 426 329 426 754 450 450 583 629 548 629 572 387 629 654 342 325 624 342 952 654 600 629 629 474 506 416 654 523 774 536 523 511 579 327 579 754 ]
 ]
/CIDToGIDMap 11 0 R
>>
endobj
8 0 obj
<</Length 346>>
stream
/CIDInit /ProcSet findresource begin
12 dict begin
begincmap
/CIDSystemInfo
<</Registry (Adobe)
/Ordering (UCS)
/Supplement 0
>> def
/CMapName /Adobe-Identity-UCS def
/CMapType 2 def
1 begincodespacerange
<0000> <FFFF>
endcodespacerange
1 beginbfrange
<0000> <FFFF> <0000>
endbfrange
endcmap
CMapName currentdict /CMap defineresource pop
end
end

endstream
endobj
9 0 obj
<</Registry (Adobe)
/Ordering (UCS)
/Supplement 0
>>
endobj
10 0 obj
<</Type /FontDescriptor
/FontName /MPDFAA+DejaVuSerifCondensed-Bold
 /CapHeight 729
 /XHeight 519
 /FontBBox [-752 -389 1617 1145]
 /Flags 262148
 /Ascent 939
 /Descent -236
 /Leading 0
 /ItalicAngle 0
 /StemV 165
 /MissingWidth 540
 /Style << /Panose < 0 0 2 6 8 6 5 6 5 2 2 4> >>
/FontFile2 12 0 R
>>
endobj
11 0 obj
<</Length 304
/Filter /FlateDecode
>>
stream
x����V
```

**Comment by creecros** [comment]
I promise I'll take a look, just haven't had a chance. This week most likely.

**Comment by creecros** [comment]
@Teolone88 Before we get to the gibberish part.

Is this code supposed to work? It's full of errors, incorrect var usage, etc. Am I supposed to be fixing that as well? Or is that code not up to date?

Right off the bat:
```
,
PHP message: PHP Warning:  Undefined variable $project in /var/www/app/plugins/Invoicer/Template/invoice.php on line 1",
PHP message: PHP Warning:  Trying to access array offset on null in /var/www/app/plugins/Invoicer/Template/invoice.php on line 5"
```

Then after that:
```
Fatal error: Uncaught ArgumentCountError: Too few arguments to function Kanboard\Plugin\Invoicer\Controller\InvoiceModalController::printProjectInvoice(), 0 passed in /var/www/app/app/Core/Controller/Runner.php on line 77 and exactly 2 expected in /var/www/app/plugins/Invoicer/Controller/InvoiceModalController.php:27 Stack trace: #0 /var/www/app/app/Core/Controller/Runner.php(77): Kanboard\Plugin\Invoicer\Controller\InvoiceModalController->printProjectInvoice() #1 /var/www/app/app/Core/Controller/Runner.php(31): Kanboard\Core\Controller\Runner->executeController() #2 /var/www/app/index.php(9): Kanboard\Core\Controller\Runner->execute() #3 {main} thrown in /var/www/app/plugins/Invoicer/Controller/InvoiceModalController.php on line 27
```

just want to make sure I'm doing work that has already been corrected.

```
Application version: v1.2.37
PHP version: 8.3.7
PHP SAPI: fpm-fcgi
HTTP Client: cURL
OS version: Linux 5.10.102.1-microsoft-standard-WSL2
Database driver: sqlite
Database version: 3.45.3
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
```

**Comment by Teolone88** [comment]
Yes, that is known. I did not update. It's easy to fix. All I need is the gibberish.
I have tried JS libraries but they do not work either like html2pdf.js

**Comment by creecros** [comment]
Then fix that, so I can get to the issue at hand.

**Comment by Teolone88** [comment]
I have manage with the below js libraries:

- jspdf.umd.min.js
- html2canvas.min.js
- jspdf-html2canvas.min.js

Plus the below script:

```
function Convert_HTML_To_PDF() {
window.jsPDF = window.jspdf.jsPDF;
var doc = new jsPDF('p', 'mm', ['297 ','350']);
// Source HTMLElement or a string containing HTML.
var elementHTML = document.querySelector("#wrapper");

doc.html(elementHTML, {
    callback: function(doc) {
        // Save the PDF
        doc.save('invoice.pdf');
    },
        margin: [1, 1, 1, 1],
        autoPaging: 'text',
        x: 1,
        y: 1,
        width: 200, //target width in the PDF document
        windowWidth: 675 //window width in CSS pixels
});
}
```

Here the HTML rendered after the form where the div #wrapper is served to the jsPDF library.

```
<div id="wrapper">
    <div id="pspdfkit-header">
      <div class="header-columns">
        <div class="logoty">
          <img class="logo" src="/client-area/?controller=CustomizerFileController&action=image&plugin=customizer&file_id=1" />
        </div>

        <div>
          <p>
          <?= $this->text->e($values['invFromName']) ?><br>
<?= $this->text->e($values['invFromAddress1']) ?><br>
<?= $this->text->e($values['invFromCountry']) ?><br>
<?= t('VAT ID:  ') ?><?= $this->text->e($values['invFromVAT']) ?>
          </p>
        </div>
      </div>
    </div>
    <div class="page" style="page-break-after: always">
      <div>
        <h2><?= t('Invoice #:  ') ?><?= $values['invDate'] . '-' . $this->text->e($project['name']). '-' . $this->text->e($project['id']) ?> <br />
<?= t('Created:  ') ?><?= $values['invDate'] ?></h2>
      </div>

      <div class="intro-table">
        <div class="intro-form intro-form-item">
          <p class="intro-table-title">Billed To:</p>
          <p>
          <?= $this->text->e($values['invToName']) ?><br>
<?= $this->text->e($values['invToAddress1']) ?><br>
<?= $this->text->e($values['invToCountry']) ?><br>
<?= t('VAT ID:  ') ?><?= $this->text->e($values['invToVAT']) ?>
          </p>
        </div>

        <div class="intro-form">
          <div class="intro-form-item-border">
            <p class="intro-table-title">Payment Due:</p>
            <p><?= $values['invDue'] ?></p>
          </div>

          <div class="intro-form-item-border">
            <p class="intro-table-title">Payment Method:</p>
            <p>Bank Transfer</p>
          </div>
        </div>
      </div>

      <div class="table-box">
        <table cellpadding="0" cellspacing="0" id="empTable">
          <tbody>
            <tr class="heading">
              <td></td>
              <td>Description</td>
              <td>Price</td>
            </tr>
            <p>
              <input 
                type="button" 
                id="addRow" 
                value="Add New Item" 
                onclick="addRow()" />
            </p>

            <?php foreach($values['invAdd'] as $task): ?>
<tr class="item">
<td><input type="text"  value="" /></td>
<td><input type="text"  value="<?= t($task) ?>" /></td>
<td><?= t('100') ?></td>
</tr>
<?php endforeach; ?>
          </tbody>
        </table>
      </div>

      <div class="summary-box">
        <table cellpadding="0" cellspacing="0">
          <tbody>
            <tr class="item">
              <td></td>
              <td>Subtotal:</td>
              <td><input type="text"  value="" /></td>
            </tr>

            <tr class="item">
              <td></td>
              <td>Discount:</td>
              <td><input type="text"  value="" /></td>
            </tr>

            <tr class="item">
              <td></td>
              <td>Subtotal Less Discount:</td>
              <td><input type="text"  value="" /></td>
            </tr>

            <tr class="item">
              <td></td>
              <td>Total Tax:</td>
              <td><input type="text"  value="" /></td>
            </tr>

            <tr class="no-border-item">
              <td></td>
              <td>Total Due:</td>
              <td><input type="text"  value="" /></td>
            </tr>

          </tbody>
        </table>
      </div>
    </div>

    <div class="page" style="page-break-after: always">
      <div class="form">
        <label for="notes" class="label"> Notes: </label>
        <input type="text" id="notes" class="border-bottom" value="" />
      </div>

      <div class="signer">
        <div class="form signer-item">
          <label for="date" class="label">Date:</label>
          <input type="text" id="date" class="border-bottom" value="01/01/2021" />
        </div>

        <div class="form signer-item">
          <label for="signature" class="label">Issued by:</label>
          <input type="text" id="signature" class="border" value="Sign Here" />
        </div>
      </div>
    </div>

    <div id="pspdfkit-footer">
      <div class="footer-columns">
        <span>Invoice</span>
      </div>
    </div>
  </div>

```

I know is ugly but it kinda work.
![image](https://github.com/creecros/Task2pdf/assets/36920983/bbbdadd1-77f4-479f-9fd3-7cda7ddb9e22)

Unfortunately I am facing issues in loading correctly the CSS now. What a pickle this project.

I have updated the template, but the domPDF class is still there and if I render and stream, I get gibberish.

![image](https://github.com/creecros/Task2pdf/assets/36920983/0ab8d47c-a29f-4301-9a50-54e54443815c)

**Comment by creecros** [comment]
@Teolone88 

I'm not sure you understood my previous ask.

I am here to help you get dompdf to work. Why did you remove the "Create Invoice" link? 

I was hoping you were going to provide me with code that was failing at dompdf, but currently this code doesn't even get me to point to test it and see what the problem is. Can we focus on that?

I mean, how are you even trying to render using dompdf if there is no means to get there? your modal is asking for vars you can't even send to it. Hence the `Fatal error: Uncaught ArgumentCountError: Too few arguments to function`

And even if you are somehow bypassing something to get that controller to operate, there is a 0% chance that you are sending those argumenets an array, for `$project` and `$values` in `public function printProjectInvoice($project, $values)`

So IF you are somehow forcing that controller to run, ya, i bet you are getting gibberish, but to be honest, i can't even imagine how it could run.

**Comment by Teolone88** [comment]
I am not a developer and I'm trying my best. I am sure there is a better way. All I wanted was to have the form that take the tasks of the project and send them to the pdf library to print.
I am sorry if I oversold it but that is the state at the moment.
However, the array is passed as the invoice in html is prepopulating those task in the item line but the PDF library is not rendering correctly. I am sure is my fault as your plugin works correctly.

**Comment by creecros** [comment]
Where is this form you speak of?

**Comment by creecros** [comment]
> However, the array is passed as the invoice in html is prepopulating those task

If you are passing an array via a form, great, but your controller is not grabbing those values. As "Values" from a form it is possible, but definately not `$project`. As `$values` you cannot do it as a argument, you have to grab those after the controllers arguments. i.e. `$values = $this->getValues();`, and that is assuming the values were sent by the form in the correct manner. But, I do not know what form we are talking about, as I do not see a way to get to a form.

**Comment by Teolone88** [comment]
Here is the structure.
`Plugin.php` contains those hooks

`$this->template->hook->attach('template:project:dropdown', 'Invoicer:project_header/buttonInvoice');`  which is the button in the dropdown in the project (Like your but below after gannt).

**You need to be admin to see the button (Stupid me!!)**
```
        <?php if ($this->user->isAdmin()): ?>
            <li>
                <?= $this->modal->large('file-pdf-o', t('Create Invoice'), 'InvoiceModalController', 'configInvoice', array('plugin' => 'Invoicer', 'project_id' => $project['id'])) ?>
            </li>
        <?php endif ?>
```

This open the modal with the form available in Template->project_header->createinvoice.php with the below form for the controller `InvoiceModalController` with the method `configInvoice` which render the form.

```
    public function configInvoice()
    {
    	$status = array(TaskModel::STATUS_OPEN);
    	$project = $this->getProject();

    	$task_ids = $this->db
        ->table(TaskModel::TABLE)
        ->eq(TaskModel::TABLE.'.project_id', $project['id'])
        ->in(TaskModel::TABLE.'.is_active', $status)
        ->asc(TaskModel::TABLE.'.id')
        ->findAllByColumn(TaskModel::TABLE.'.title');
    	
        $this->response->html($this->template->render('Invoicer:project_header/createInvoice', array(
        'project' => $project,
        'values' => array(
            	'invRef' 			=> $project['name'] . '-' . $project['id'],
            	'invFromName' 		=>  '1',
            	'invFromAddress1'	=>  '2',
            	'invFromAddress2' 	=>  '3',
            	'invFromCityZip' 	=>  '4',
            	'invFromCountry' 	=>  '5',
            	'invFromVAT' 		=>  '6',
            	'invToName' 		=>  '7',
            	'invToAddress1' 	=>  '8',
            	'invToAddress2' 	=>  '9',
            	'invToCityZip' 		=>  '10',
            	'invToCountry'		=>  '11',
            	'invToVAT' 			=>  '12',
            	'invDate' 			=> date('Y-m-d'),
            	'invDue' 			=> date('Y-m-d',strtotime('+30 days')),
        		'invAdd' 			=> $task_ids,
            ),	
        )));
    }
```

The form action invoke the controller `InvoiceModalController` with the method `invoiceProjectOpen` with a `post` request
```
<div class="page-header">
    <h2><?= 'Invoice for Project: '. $project['name'] ?></h2>
</div>
<form action="<?= $this->url->href('InvoiceModalController', 'invoiceProjectOpen', array('plugin' => 'Invoicer', 'project_id' => $project['id'], 'values' => $values)) ?>" method="post" autocomplete="off">
	<?= $this->form->csrf() ?>
	<?= $this->form->label(t('Reference'), 'invRef') ?>
	<?= $this->form->text('invRef', $values, array('required'), array('placeholder="'.t('invRef').'"', 'aria-label="'.t('Search').'"')) ?>
	<?= $this->form->label(t('From'), 'invFrom') ?>
	<?= $this->form->text('invFromName', $values,  array('required'), array('placeholder="'.t('Name').'"', 'aria-label="'.t('Search').'"')) ?>
	<?= $this->form->text('invFromAddress1', $values,  array('required'), array('placeholder="'.t('Address 1').'"', 'aria-label="'.t('Search').'"')) ?>
	<?= $this->form->text('invFromAddress2', $values,  array('required'), array('placeholder="'.t('Address 2').'"', 'aria-label="'.t('Search').'"')) ?>
	<?= $this->form->text('invFromCityZip', $values,  array('required'), array('placeholder="'.t('City & Zip').'"', 'aria-label="'.t('Search').'"')) ?>
	<?= $this->form->text('invFromCountry', $values,  array('required'), array('placeholder="'.t('Country').'"', 'aria-label="'.t('Search').'"')) ?>
	<?= $this->form->text('invFromVAT', $values,  array('required'), array('placeholder="'.t('VAT').'"', 'aria-label="'.t('Search').'"')) ?>
	<?= $this->form->label(t('To'), 'invFrom') ?>
	<?= $this->form->text('invToName', $values,  array('required'), array('placeholder="'.t('Name').'"', 'aria-label="'.t('Search').'"')) ?>
	<?= $this->form->text('invToAddress1', $values,  array('required'), array('placeholder="'.t('Address 1').'"', 'aria-label="'.t('Search').'"')) ?>
	<?= $this->form->text('invToAddress2', $values,  array('required'), array('placeholder="'.t('Address 2').'"', 'aria-label="'.t('Search').'"')) ?>
	<?= $this->form->text('invToCityZip', $values,  array('required'), array('placeholder="'.t('City & Zip').'"', 'aria-label="'.t('Search').'"')) ?>
	<?= $this->form->text('invToCountry', $values,  array('required'), array('placeholder="'.t('Country').'"', 'aria-label="'.t('Search').'"')) ?>
	<?= $this->form->text('invToVAT', $values,  array('required'), array('placeholder="'.t('VAT').'"', 'aria-label="'.t('Search').'"')) ?>
	<?= $this->form->label(t('Date'), 'invDate') ?>
	<?= $this->form->date('invDate', $values, array('required'), array('placeholder="'.t('Invoice Date (Y-m-d)').'"', 'aria-label="'.t('Search').'"')) ?>
	<?= $this->form->label(t('Due'), 'invDue') ?>
	<?= $this->form->date('invDue', $values, array('required'), array('placeholder="'.t('Due Date (Y-m-d)').'"', 'aria-label="'.t('Search').'"')) ?>
	<?= $this->form->label(t('Add'), 'invAdd') ?>
	<?= $this->form->select2(true, 'invAdd', $values['invAdd'], array('required'), array('placeholder="'.t('Add Item').'"', 'aria-label="'.t('Search').'"')) ?>
    <?= $this->modal->submitButtons() ?>
</form>
<br><br>
<?php
```

The above controller is supposed to pull the values (pre-populated) and pass them to the method `invoiceProjectOpen` which pass them again to the function `printProjectInvoice`.

```
    public function invoiceProjectOpen($project = null, array $values = array())
    {
        $project = $this->getProject();
    	$values =  $this->request->getValues();                     
                           
    	$this->flash->success(t('Data Submitted'));
        self::printProjectInvoice($project, $values);
    }
```

**Comment by Teolone88** [comment]
However, values or not values, even with a pre-defined values the domPDF will throw weird characters in the stream. Even using the example available online. That is what I do not understand. There must be a passage that I am not following, or maybe the versioning of the library is defected.

**Comment by creecros** [comment]
Ok, so as far as errors go, you are plagued with them, like A LOT! That said, your gibberish is due to using a modal. Don't do that.

**Comment by Teolone88** [comment]
How can i close the modal once i pass the values?
Could you help me there?

**Comment by creecros** [comment]
I dont think you can, if so I simply don't know.

I simply removed the modal all together.

**Comment by Teolone88** [comment]
I have managed in the end. Not sure if you are interested in such a thing

![image](https://github.com/creecros/Task2pdf/assets/36920983/9d93ec4f-3d09-4481-948e-9660e07949c8)

![image](https://github.com/creecros/Task2pdf/assets/36920983/b454fee1-046d-4582-9503-3ca22c6aa2c8)

It gets some preview from the task in the colored labels, if you hove, so that you can write a proper invoice.

The PDF template is still crap but another day.

Thank you again if I wasted your time last day.

Best,

Teo

**Comment by creecros** [comment]
No worries, nothing was waisted since we got to the route of your problem. Glad you got it 👍.
